import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <header>
          <div id='logo'>TS VCS</div>
          <div id='btnBox'>
            <input type='button' id='ALPHA' value="ALPHA"/>
            <input type='button' id='AMARANCE' className='active' value="AMARANCE"/>
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
